version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "1339:1339"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: sh -c "npm install -g serve && serve -s . -l 8080"
    depends_on:
      - backend
